package io.github.dsudomoin.migration.kora

import io.github.dsudomoin.migration.ScriptPolicy
import ru.tinkoff.kora.config.common.annotation.ConfigValueExtractor

/**
 * HOCON-конфиг runner'а. Секция `migration { ... }` в `application.conf`.
 *
 * Минимум для запуска — `migration.run = ${?MIGRATION_RUN}`. Остальное опционально.
 *
 * Объявлен интерфейсом с default-методами и помечен [ConfigValueExtractor], а не `@ConfigSource`.
 * Это канонический для Kora способ описать конфиг, приезжающий в чужой сервис из библиотеки —
 * ровно так устроены `JdbcDatabaseConfig` и `JdbcDatabaseModule` в самой Kora. Две причины, и обе
 * проверены на живом графе:
 * - `@ConfigSource` генерирует отдельный модуль для конфига САМОГО приложения; у потребителя
 *   сборка графа падала с «Component was expected to be generated by extension but was not»;
 * - генератор KSP не видит дефолтных значений параметров конструктора Kotlin-класса, поэтому
 *   `dryRun: Boolean = false` в `data class` превращался в обязательный ключ, и отсутствие
 *   `migration.dryRun` в конфиге роняло старт. Дефолт, объявленный телом метода интерфейса,
 *   генератор учитывает.
 *
 * Для программной сборки (тесты, встраивание runner'а без HOCON) есть [MigrationConfigValues].
 */
@ConfigValueExtractor
interface MigrationConfig {

    /** Имя миграции к запуску (совпадает с [io.github.dsudomoin.migration.Migration.name]). `null` = idle. */
    fun run(): String?

    /** `true` — все write'ы через `guardWrite` пропускаются, в отчёт идёт breakdown. */
    fun dryRun(): Boolean = false

    /**
     * Папка для артефактов прогона (`migration.log`, `errors.csv`/`log`, пользовательские CSV).
     * `null` → дефолт `logs/<имя миграции>`.
     *
     * Тип — `String`, а не `java.nio.file.Path`: для `Path` в Kora нет `ConfigValueExtractor`,
     * и объявление поля этим типом роняет сборку графа у потребителя.
     */
    fun outputFolder(): String?

    /** Дефолты для `forEach`, порога ошибок и unhandled-policy. */
    fun defaults(): Defaults

    /** Тонкая настройка авто-аудитора. Пути файлов выводятся из [outputFolder]. */
    fun errorReporting(): ErrorReporting

    /** Настройки рендера итогового отчёта. */
    fun report(): Report

    /** Дефолтные параметры исполнения. */
    @ConfigValueExtractor
    interface Defaults {

        /** Политика для `migrate()`-level исключений (см. [ScriptPolicy]). */
        fun onUnhandled(): ScriptPolicy = ScriptPolicy.FAIL_FAST

        /** Если `skipped > threshold` — прервать прогон с exit 1. `0` = отключено. */
        fun errorThreshold(): Long = 0

        /** Период дефолтного `Progress.Default` логгера. */
        fun progressEvery(): Int = 1000

        /**
         * Значение аргумента `parallel` у `forEach`, если он не указан явно. Реальный
         * параллелизм каждого цикла задаёт его собственный аргумент; пул runner'а cached и
         * подстраивается под запрошенное число воркеров.
         */
        fun parallel(): Int = 1
    }

    /** Настройка авто-аудитора ошибок. */
    @ConfigValueExtractor
    interface ErrorReporting {

        /** Писать ли в `errors.log` стектрейсы. `false` = только CSV. */
        fun includeStackTrace(): Boolean = true

        /** Обрезать `itemRepr` в CSV до этой длины (с `...`). */
        fun maxItemReprLength(): Int = 500
    }

    /** Настройки итогового отчёта. */
    @ConfigValueExtractor
    interface Report {

        /** Заменить unicode-глифы в отчёте на ASCII (`✓` → `[OK]` и т.д.). */
        fun asciiOnly(): Boolean = false
    }
}

/**
 * Программная реализация [MigrationConfig] — для тестов и для запуска runner'а без HOCON.
 * В боевом сценарии конфиг собирает Kora из `application.conf`, и этот класс не нужен.
 */
data class MigrationConfigValues(
    private val run: String? = null,
    private val dryRun: Boolean = false,
    private val outputFolder: String? = null,
    private val defaults: MigrationConfig.Defaults = DefaultsValues(),
    private val errorReporting: MigrationConfig.ErrorReporting = ErrorReportingValues(),
    private val report: MigrationConfig.Report = ReportValues(),
) : MigrationConfig {
    override fun run(): String? = run
    override fun dryRun(): Boolean = dryRun
    override fun outputFolder(): String? = outputFolder
    override fun defaults(): MigrationConfig.Defaults = defaults
    override fun errorReporting(): MigrationConfig.ErrorReporting = errorReporting
    override fun report(): MigrationConfig.Report = report
}

/** Программная реализация [MigrationConfig.Defaults]. */
data class DefaultsValues(
    private val onUnhandled: ScriptPolicy = ScriptPolicy.FAIL_FAST,
    private val errorThreshold: Long = 0,
    private val progressEvery: Int = 1000,
    private val parallel: Int = 1,
) : MigrationConfig.Defaults {
    override fun onUnhandled(): ScriptPolicy = onUnhandled
    override fun errorThreshold(): Long = errorThreshold
    override fun progressEvery(): Int = progressEvery
    override fun parallel(): Int = parallel
}

/** Программная реализация [MigrationConfig.ErrorReporting]. */
data class ErrorReportingValues(
    private val includeStackTrace: Boolean = true,
    private val maxItemReprLength: Int = 500,
) : MigrationConfig.ErrorReporting {
    override fun includeStackTrace(): Boolean = includeStackTrace
    override fun maxItemReprLength(): Int = maxItemReprLength
}

/** Программная реализация [MigrationConfig.Report]. */
data class ReportValues(
    private val asciiOnly: Boolean = false,
) : MigrationConfig.Report {
    override fun asciiOnly(): Boolean = asciiOnly
}
